# Generated by Django 5.1.1 on 2024-09-30 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almoxarifados',
            fields=[
                ('id_almoxarifado', models.AutoField(primary_key=True, serialize=False)),
                ('nome_almoxarifado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nome_material', models.CharField(max_length=50)),
                ('unidade_compra', models.CharField(max_length=2)),
                ('unidade_requisicao', models.CharField(max_length=2)),
                ('qtde_estoque', models.IntegerField()),
                ('inativo', models.BooleanField()),
                ('id_empresa', models.IntegerField()),
                ('id_almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.almoxarifados')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.grupo')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id_nota_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('nome_nota_fiscal', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField()),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.materiais')),
            ],
        ),
        migrations.CreateModel(
            name='Requisicoes',
            fields=[
                ('id_requisicao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_requisicao', models.CharField(max_length=50)),
                ('id_responsavel', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.materiais')),
            ],
        ),
    ]
