# Generated by Django 5.1.1 on 2024-10-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Grupo',
            new_name='Grupos',
        ),
        migrations.RenameModel(
            old_name='NotaFiscalEntrada',
            new_name='NotasFiscaisEntrada',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Tipos',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='id_tipo',
            new_name='id_categoria',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='nome_tipo',
            new_name='nome_categoria',
        ),
        migrations.RenameField(
            model_name='tipos',
            old_name='id_categoria',
            new_name='id_tipo',
        ),
        migrations.RenameField(
            model_name='tipos',
            old_name='nome_categoria',
            new_name='nome_tipo',
        ),
    ]
