# Generated by Django 5.1.1 on 2024-10-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_rename_tipo_categorias_rename_grupo_grupos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiais',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.tipos'),
        ),
    ]
