# Generated by Django 5.1.1 on 2024-10-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_empresa_alter_materiais_id_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_empresa',
            new_name='razao_social',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=14),
        ),
    ]
